config/routes.rb
Rails.application.routes.draw do
  resources :blockships
  devise_for :users
  resources :followships
  resources :tweets
  resources :friends

  root 'tweets#show_friends_tweets'

  get ':username' => 'tweets#show_username_tweets',:as =>'username'

end

app/models/followship.rb
class Followship < ActiveRecord::Base
  belongs_to :follower, :class_name => "User"
  belongs_to :following, :class_name => "User"
end

app/controllers/followships_controller.rb
class FollowshipsController < ApplicationController
  before_action :set_followship, only: [:show, :destroy]

  # GET /followships
  # GET /followships.json
  def index
    # arr.each_index.select{|i| arr[i] == 'x'}
    @followships = Followship.select{|followship| followship.follower_id == current_user.id}
  end

  # GET /followships/1
  # GET /followships/1.json
  def show
  end

  # GET /followships/new
  def new
    @friendship_opportunities, friends, blockers, blockeds = [], [], [], []
    for followship in current_user.followingships
      friends.append(followship.following)
    end
    for blockship in current_user.blockerships
      blockers.append(blockship.blocker)
    end
    for blockship in current_user.blockedships
      blockeds.append(blockship.blocked)
    end
    for user in User.all
      if not(friends.include?(user) or blockeds.include?(user) or blockers.include?(user) or user == current_user)
        @friendship_opportunities.append(user)
      end
    end
    @followship = Followship.new
  end

  # POST /followships
  # POST /followships.json
  def create
    @followship = Followship.create(:follower_id => current_user.id, :following_id => followship_params[:following_id])

    respond_to do |format|
      if @followship.save
        format.html { redirect_to @followship, notice: 'Followship was successfully created.' }
        format.json { render :show, status: :created, location: @followship }
      else
        format.html { render :new }
        format.json { render json: @followship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followships/1
  # DELETE /followships/1.json
  def destroy
    @followship.destroy
    respond_to do |format|
      format.html { redirect_to followships_url, notice: 'Followship was successfully unfollowed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_followship
      @followship = Followship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def followship_params
      params.require(:followship).permit(:follower_id, :following_id)
    end
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/views/followships/_form.html.erb
<%= form_for(@followship) do |f| %>
  <% if @followship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@followship.errors.count, "error") %> prohibited this followship from being saved:</h2>

      <ul>
      <% @followship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :following_id %><br>
    <%= f.select :following_id, options_for_select(@friendship_opportunities.map{|user| ["#{user.email}", user.id]}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/followships/index.html.erb
<h1>Listing My Followings</h1>

<table>
  <thead>
    <tr>
      <th>Follower</th>
      <th>Following</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @followships.each do |followship| %>
      <tr>
        <td><%= followship.follower.email %></td>
        <td><%= followship.following.email %></td>
        <td><%= link_to 'Unfollow', followship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Followship', new_followship_path %>

app/views/followships/new.html.erb
<h1>New Followship</h1>

<%= render 'form' %>

<%= link_to 'Back', followships_path %>

app/views/followships/show.html.erb
<p>
  <strong>Follower:</strong>
  <%= @followship.follower.email %>
</p>

<p>
  <strong>Following:</strong>
  <%= @followship.following.email %>
</p>

<%= link_to 'Edit', edit_followship_path(@followship) %> |
<%= link_to 'Back', followships_path %>