config/routes.rb
Rails.application.routes.draw do
  resources :blockships
  devise_for :users
  resources :followships
  resources :tweets
  resources :friends

  root 'tweets#show_friends_tweets'

  get ':username' => 'tweets#show_username_tweets',:as =>'username'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.select { |tweet| tweet.user_id == current_user.id }
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(:user_id => current_user.id, :text => tweet_params[:text])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_friends_tweets
    @user_tweets = []
    tweets = []
    for followship in current_user.followingships
      tweets.concat(followship.following.tweets)
    end
    sorted_tweets = tweets.sort_by{|tweet| tweet[:created_at]}.reverse
    # sorted_tweets = tweets.order('created_at DESC')
    sorted_tweets.each do |tweet|
      @user_tweets.append({:user => User.find(tweet.user_id), :tweet => tweet})
    end
  end

  def show_username_tweets
    exists = false;
    for followship in current_user.followingships
      if followship.following.email == params[:username]+'@gmail.com'
        exists = true;
      end
    end
    if exists == true
      all_tweets = User.find_by_email(params[:username]+'@gmail.com').tweets
      all_tweets = all_tweets.order('created_at DESC')
      @return_value = {:is_valid => 'allowed', :tweets => all_tweets}
    else
      all_tweets = []
      @return_value = {:is_valid => 'not allowed', :tweets => all_tweets}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :text)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text, :size => 140, :maxlength => 140 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing My Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.text %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p>
  <strong>User:</strong>
  <%= @tweet.user.email %>
</p>

<p>
  <strong>Text:</strong>
  <%= @tweet.text %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/show_friends_tweets.html.erb
<h1>Listing Friends's Tweets</h1>

<table>
  <thead>
  <tr>
    <th>User</th>
    <th>Text</th>
    <th>Date Created</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @user_tweets.each do |user_tweet| %>
      <tr>
        <td><%= user_tweet[:user].email %></td>
        <td><%= user_tweet[:tweet].text %></td>
        <td><%= user_tweet[:tweet].created_at %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<%= link_to 'My Tweets', tweets_path %>

app/views/tweets/show_username_tweets.html.erb
<h1>Listing <%=params[:username]%>'s Tweets</h1>

<div>you are <%=@return_value[:is_valid]%> to see <%=params[:username]%>'s tweets.</div><br>
<table>
  <thead>
  <tr>
    <th>Text</th>
    <th>Date Created</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @return_value[:tweets].each do |tweet| %>
      <tr>
        <td><%= tweet.text %></td>
        <td><%= tweet.created_at %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<%= link_to 'My Tweets', tweets_path %>