config/routes.rb
Rails.application.routes.draw do
  resources :blockships
  devise_for :users
  resources :followships
  resources :tweets
  resources :friends

  root 'tweets#show_friends_tweets'

  get ':username' => 'tweets#show_username_tweets',:as =>'username'

end

app/models/blockship.rb
class Blockship < ActiveRecord::Base
  belongs_to :blocker, :class_name => "User"
  belongs_to :blocked, :class_name => "User"
end

app/controllers/blockships_controller.rb
class BlockshipsController < ApplicationController
  before_action :set_blockship, only: [:show, :destroy]

  # GET /blockships
  # GET /blockships.json
  def index
    @blockships = Blockship.select{|blockship| blockship.blocker_id == current_user.id}
  end

  # GET /blockships/1
  # GET /blockships/1.json
  def show
  end

  # GET /blockships/new
  def new
    @blockship_opportunities, blockeds = [], []
    for blockship in current_user.blockedships
      blockeds.append(blockship.blocked)
    end
    for user in User.all
      if not(blockeds.include?(user) or user == current_user)
        @blockship_opportunities.append(user)
      end
    end
    @blockship = Blockship.new
  end

  # POST /blockships
  # POST /blockships.json
  def create

    for followship in current_user.followerships
      if followship.follower_id.to_s === blockship_params[:blocked_id]
        followship.destroy
      end
    end
    for followship in current_user.followingships
      if followship.following_id.to_s === blockship_params[:blocked_id]
        followship.destroy
      end
    end


    @blockship = Blockship.create(:blocker_id => current_user.id, :blocked_id => blockship_params[:blocked_id])

    respond_to do |format|
      if @blockship.save
        format.html { redirect_to @blockship, notice: 'Blockship was successfully created.' }
        format.json { render :show, status: :created, location: @blockship }
      else
        format.html { render :new }
        format.json { render json: @blockship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blockships/1
  # DELETE /blockships/1.json
  def destroy
    @blockship.destroy
    respond_to do |format|
      format.html { redirect_to blockships_url, notice: 'Blockship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blockship
      @blockship = Blockship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blockship_params
      params.require(:blockship).permit(:blocker_id, :blocked_id)
    end
end

app/helpers/blockships_helper.rb
module BlockshipsHelper
end

app/views/blockships/_form.html.erb
<%= form_for(@blockship) do |f| %>
  <% if @blockship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blockship.errors.count, "error") %> prohibited this blockship from being saved:</h2>

      <ul>
      <% @blockship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :blocked_id %><br>
    <%= f.select :blocked_id, options_for_select(@blockship_opportunities.select{|user| user.id != current_user.id}.map{|user| ["#{user.email}", user.id]}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blockships/index.html.erb
<h1>Listing My Blocked Users</h1>

<table>
  <thead>
    <tr>
      <th>Blocker</th>
      <th>Blocked</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blockships.each do |blockship| %>
      <tr>
        <td><%= blockship.blocker.email %></td>
        <td><%= blockship.blocked.email %></td>
        <td><%= link_to 'Unblock', blockship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blockship', new_blockship_path %>

app/views/blockships/new.html.erb
<h1>New Blockship</h1>

<%= render 'form' %>

<%= link_to 'Back', blockships_path %>

app/views/blockships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Blocker:</strong>
  <%= @blockship.blocker.email %>
</p>

<p>
  <strong>Blocked:</strong>
  <%= @blockship.blocked.email %>
</p>

<%= link_to 'Edit', edit_blockship_path(@blockship) %> |
<%= link_to 'Back', blockships_path %>